apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    app: sales

  type: ClusterIP
# What we are saying here is that we want to expose the service 
# on port 3000 & 4000 inside the cluster
  ports:
  - name: sales-api
    port: 3000
    targetPort: sales-api
  - name: sales-api-debug
    port: 4000
    targetPort: sales-api-debug
