apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# We bring here the base sales yaml first
- ../../base/sales/
patches:
# We say here patch that with what in the deploy file
- path: ./dev-sales-patch-deploy.yaml
# Replace the service image that we defined in the base
# With that name and tag
images:
- name: service-image
  newName: ardanlabs/service/sales-api
  newTag: 0.0.1
