apiVersion: v1
kind: Namespace
# We are defining here a namespace sp we don't run in the default one
metadata:
  name: sales-system
--- # This means we are starting a new file if we remove these dashes we will get an error
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      terminationGracePeriodSeconds: 60
      
      containers:
      - name: sales-api
        image: service-image

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
 